### PR TITLE
TFT display module

### PR DESCRIPTION
**Pull request by patryk3211**
This PR adds support for using a TFT display with the LVGL module

### CODE REVIEW

**Comment by Paciente8159** [comment]
Greate work.
The only observation I have to make as far as I can tell is that this that the event listener with lock should take in consideration the used port (hw spi spi2 or sw spi)

**Comment by Paciente8159** [comment]
I've tested the code and there are several issues with it.
After fixing them I was able to get it to work.

I really like the Windows95 vibe.

**Comment by patryk3211** [comment]
Listener lock now changes depending on the selected port, hardware port is selected through a number and the new method for display creation is implemented.

**Comment by patryk3211** [comment]
> I've tested the code and there are several issues with it. After fixing them I was able to get it to work.
> 
> I really like the Windows95 vibe. 

Looks like you have the red and blue channels swapped.

**Comment by Paciente8159** [comment]
I think they are hardware swapped. I need to see if I can fix it via configuration.

**Comment by patryk3211** [comment]
The `LV_LCD_FLAG_BGR` flag in display create should fix that.

**Comment by patryk3211** [comment]
I've switched tft_update to run on cnc_io_dotasks to fix the following issue:
When a partial redraw is happening LVGL will wait for a display to finish flushing by looping cnc_dotasks. This is fine except when in the middle of a redraw, an alarm gets triggered (or anything that breaks the loop). Because tft_update was running on cnc_dotasks it was not getting run because cnc_dotasks was trying to go into the error loop, but because the drawing never finished, it could never finish running the event listener of lvgl_update and it deadlocked.

**Comment by Paciente8159** [comment]
> The `LV_LCD_FLAG_BGR` flag in display create should fix that.

That even makes the problem worse. I have no idea what is the pixel format on this screen.

**Comment by Paciente8159** [comment]
Still doesn't work. I had to once again re-apply the modifications to both `lvgl_cmd_cb` and `lvgl_pixel_cb` like shown above and had to define manually the backlight pin and enable that output.

**Comment by patryk3211** [comment]
I don't see any code reviews.

**Review by Paciente8159 — CHANGES_REQUESTED** [review]
You are correct. They were still pending. Here are the reviews

**Comment by patryk3211** [comment]
Should be fine now. Let me know if the backlight pin is correct (currently set high on display init)

**Review by Paciente8159 — APPROVED** [review]

**Comment by Paciente8159** [comment]
I'm still having issues on my display but it's a hardware thing (I think). I think my screen is BRG or GRB or something like that.

**Pull request merged**
