### PR TITLE
LVGL module

### PR DESCRIPTION
**Pull request by patryk3211**
This PR adds support for using LVGL to build GUIs. There is also an implementation which imitates the Win95 look.

### CODE REVIEW

**Comment by patryk3211** [comment]
Just need to add some docs

**Comment by patryk3211** [comment]
On my hardware setup this module currently works correctly. It should be ready for merge. Now the only thing that remains is to create a better theme which supports different arrangements and configurations.

**Comment by patryk3211** [comment]
I'll try to quickly measure its execution time and see if it doesn't break the interpolator.

**Comment by patryk3211** [comment]
Here are some measurements taken from an STM32F411, the provided times are the maximum periods between executions of the `cnc_dotasks` function while a redraw is happening, only times above 5ms are printed.
- Partial idle redraw: <= 6ms
- Switching into a new list menu: ~25ms (or more depending on the number of items)
- Switching into a precomputed (e.g. idle) menu: ~9-10ms
- Switching into a precomputed list menu: ~6-9ms
All in all, the max time I measured was about 30ms. When rebuilding a list menu, time above 10ms was measured twice, after that everything goes back to normal.

**Comment by Paciente8159** [comment]
25ms could lead to motion hickups from the interpolator getting starved.
If you experience issues this [option](https://github.com/Paciente8159/uCNC/blob/28bfcb9fa7a92b45794d5761ee477033276567fd/uCNC/cnc_config.h#L517) moves the interpolator calculations to the RTC ISR.

**Comment by Paciente8159** [comment]
I don't like the 2 part module declaration. This makes it hard to integrate in the web builder for configuration.

Maybe a better alternative would be to make the display module be integrated like an overwrite callback instead of a DECL_MODULE?

**Comment by patryk3211** [comment]
Should be fine now.

**Pull request merged**
